### ISSUE TITLE
Error decoding JSR

### ISSUE THREAD

**Issue by andreamazzai** [Nectivio/65C02-Tool#1] opened 2022-02-20 15:49 UTC
I am experiencing what I *believe* is a bug in 65C02-Tool, because I tried to find the cause of the issue in everything else around the tool (details later), but did not come out with any solution.

It looks like the monitor prints a wrong value for the JSR address - SOMETIMES... but, given the same source code, always (as far as I could see) at the same point.

In example:

8000	r	a2	ff		LDX	#$ff
8002	r	9a			TXS	
8003	r	a9				
8003	r	a9	ff		LDA	#$ff
8005	r	8d	02	60	STA	$6002
6002	W	ff				
8008	r	a9	e0		LDA	#$e0
800a	r	8d	03	60	STA	$6003
6003	W	e0				
800d	r	a9	38		LDA	#$38
800f		r	20	b0	41	JSR	$41b0     <<<<---- wrong address printed here, but next instruction location address (82b0) is OK
01ff		W	80				
01fe		W	11				
8011	r	82				
82b0	r	20	de	43	JSR	$43de     <<<<---- wrong address printed here, but next instruction location address (82de) is OK
01fd		W	82				
01fc		W	b2				
82b2	r	82				
82de	r	48			PHA	
82df		r	ad				
01fb		W	38				
82df		r	ad	02	60	LDA	$6002
6002	r	ff				

My code is pretty simple (after a lot of work to remember and get to master again some C64 coding). It prints "ABCDEFGHIJKLMNOP" on the LCD and then it shifts all characters one position to the left, WITHOUT using LCD functions, and the first character is moved to the 16th position and so on. I know, I know it is not optimized... it could seem a little bit "childish"... I am just re-learning to code and I need to see things done in my own code before I can get those same things done in HW 😀.

In the attached XLS, please see sheet "**Two runs from Nectivio monitor**". These are two runs, SAME code, except that in the code on the right I did not remove the source code that I did not use and used instead a couple of JMP to jump over the routines that I did not use, hence the addresses for later subroutines changed, but the code run is the same. Proof is that you can compare the two runs and you will the see the same opcode both on the left and right side.
Anyway let's call the two source codes "**Left**" and "**Right**".

Filter by "JSR" in Column H and you will see in columns J and X the different behavior: at the beginning of the code, there are less BAD behavior rows in the Left code.

I tried to find some "pattern" in the behavior by correlating previous and next instructions and also checking if a JSR was the previous operation... I tried to see if the wrong behavior was maybe caused from a specific, previous calling JSR... it's not. I can't find any pattern.

Then look at "**Nectivio Mon different ROMs**" sheet. I placed the SAME "**Left**" source code in 4 different ROM addresses (and also one run of **Right** source code). Interestingly enough, the same "**Left**" source code, when run in different ROM locations, always results in the same wrong or good JSR behavior at the same point. See for yourself by filtering by "**JSR**" in column F and check results in H, P, X, AF columns. I hope you have a large 34", 16:9 display 😂😂😂.

- The issue only happens with a JSR instruction. When I found the issue, I blamed something wrong into my RAM / ROM / bus timing. You could easily argue that JSR is one of the few occasions that a write to RAM is made (stack), but in my code I also use PHA and PLA and I have never found an issue with PHA. Also I use RAM address $55 in zero page as a temporary store - also here no issues when writing / recovering data.
- I also tried to relocate the program in different parts of the ROM; same issue.
- Even though the monitor shows wrong JSR address, the **code runs fine**. The location address shown in the monitor for the "called" instruction after the JSR is correct.
- I was worried of some HW issues, because one day I optimized the cabling of the breadboard and I found that I did not reconnect the ground pin of the RAM chip and actually connected A13 pin to ground. More or less in the same days I started to notice the wrong behavior and I thought "mmmhhh this must be because I fried the RAM chip"; actually the circuit never stopped working and always run the code without a glitch. Also, I cannot exclude the "bug" was there before, maybe it just went unnoticed on my side. 
- Frequency is not an issue: same behavior at 1 Hz or 500 Hz.
- The code runs smooth (but I cannot monitor it 😉) also at quite high frequencies (1,000's, 10,000's or even 100,000's of Hz). I can understand it's fine by the output on the LCD.

Interestingly enough, only the HI byte of the JSR address is wrong. The LO byte is NEVER wrong.

A few days ago, I decided also to build to Ben's 8-bit computer and I ordered the kits.
Along that, I decided to order also a couple of spare RAM, ROM, 6522, CPU chips. Just to be on the safe side. When they arrived (from Jameco; less than 48 hours shipping from California to delivery to Italy) I exchanged all the chips on the breadboards (except the 74HC00 that I forgot to order). No change in the behavior.
So I decided (groan) to remove all the cabling and rebuild from scratch (except the clock module). I did that this week... still no change in the wrong behavior (2x groan).
I also had a new Arduino Mega; I suspected the one I had could be faulty. No improvements on that side.

Finally, testing with another monitor (See "Import from Wes Tool" sheet) shows that Wes tool does not show wrong behavior.

After all this troubleshooting, I believe there could be something wrong in the 65C02 tool.

If you think it could help you to better understand my messy explanation and you need to collect more details / get more clarifications, I am available for a Zoom / Teams call, whatever :-). It would be a pleasure.

Andrea
[JSR Issue.xlsx](https://github.com/Nectivio/65C02-Tool/files/8104336/JSR.Issue.xlsx)

**Comment by Nectivio** [comment] 2022-02-20 20:17
### EDIT: IGNORE THIS ENTIRE COMMENT, IT'S WRONG

----

I don't believe this is an issue that can be resolved with changes to the software.

In this line:

    * 800f r 20 b0 41 JSR $41b0 

The tool watched as the CPU read 3 bytes starting at address $800f

20 -> Which is the opcode for `JSR a` with the address specified in the next 2 bytes:
b0 -> The LSB of the address to jump to
41 -> The MSB of the address to jump to

That last byte was 0x82 in ram, which is what the CPU saw on the bus because that's the address it jumps to 4 clock cycles later, but the tool read that byte as 0x41 for some reason I can't explain.

The tool then "correctly" decoded the three bytes it saw as `JSR $41b0`

The CPU then pushes the last address of the current instruction onto the stack:

      01ff W 80
      01fe W 11

The CPU then has one 'unused' cycle, where it's not actually reading the bus, but still has the address of the last byte it read on the address bus, (mainly because that was the address still in the program counter register when it pushed the address to the stack), and r/W is high because it's not writing anymore so the tool monitors that as a bus read: 

      8011 r 82

While the CPU ignores this read... it's interesting in that, out of coincidence, it happened to be reading the one byte the tool got wrong while reading the opcode a few clock cycles earlier... and this time the tool gets the correct value here (0x82) for the high byte of the address.

So we know from this that your 6502 computer itself is working correctly and the ROM did have the correct address in memory. And in every case I investigated, the tool is correctly decoding the opcodes it's seeing on the bus.

But for some reason, when the CPU reads the second byte/high byte of a `JSR a` address, the Arduino is seeing something different on the data bus than the CPU is.

I don't think this is a timing issue. Looking at the timing diagram for the 65c02 microprocessor and the AT28C256. The CPU will setup the address bus for a read at least 10 ns before the clock goes high and hold that address until the clock goes low again. Even a very slow EEPROM should put valid data on the data bus within 350 ns of the address being valid which is at least 10 ns before the clock goes high and the tool starts reading the buses. The tool reads the address bus before the data bus, which requires at least 4 µs (i.e. 4000 ns) so the data on the data bus should be valid at the point the tool starts to read it even if you're using a very slow EEPROM.

Wes's tool doesn't output which address the Arduino sees on the data bus on the next two clock cycles immediately following the 0x20 byte for a `JSR a` instruction. It may also be reading an incorrect address there. It does confirm that the 65c02 at least read the correct instruction because it sees it jump to the correct address a few clock cycles later. Which is of course consistent with what this tool already told us, and is confirmed by the program actually outputting the correct data to the LCD.

My only theory is that this is a transient voltage drop issue. While the processor is reading the last byte of the address to jump to, it's also preparing to push the current address onto the stack as a write in the next clock cycle and pulling a fair bit of current at that exact moment. I suspect that is causing a small voltage drop system wide, and the EEPROM isn't quite driving the data bus high enough for the Arduino to register it as a high input on some of the data bits, but it's still high enough for the 65c02 to read it.

Make sure that you have several 0.1 uF bypass capacitors on your board. At least one on each power rail and preferably one right next to the 65c02 and AT28C256 chips as close as possible to the chip as you can get it.

You can also try some different power supplies for your 65c02 board and Arduino to see if that resolves the issue.

Also double check that you have a common GND connected between your board and the Arduino... you'd be surprised how often that's missed, yet the tool will still (mostly) work.

**Comment by Nectivio** [comment] 2022-02-20 21:25
OK, I see my mistake now... I had incorrectly assumed that when reading an opcode... the CPU reads the entire operand before starting to execute it.  For most instructions, that is indeed how it works, because the CPU needs to load the operand before it can do anything.

`JSR` is an exception however.

When the CPU is jumping to a subroutine, it can (and does) push the return address onto the stack before it finishes reading the address it's going to jump to.

In this sequence:

    * 800f r 20 b0 41 JSR $41b0
      01ff W 80
      01fe W 11
      8011 r 82

The third byte in the first line, that it read as (0x41) wasn't read at address 0x8011, it was read at address 0x01ff.  It doesn't read the byte at 0x8011 until the 5th clock cycle after it read the JSR instruction.

I will make an update to the ISR subroutine to correct the bug.

**Comment by andreamazzai** [comment] 2022-02-20 21:52
Thank you so much... I hope I did not ruin your Sunday because of the issue I reported... I *really* thank you from the deep of my heart for your passion and help; reading your answers (that I understood let's say about 90%) is great school for me. I hope one day I will be able to give back.

This is terrific value to learn: "When the CPU is jumping to a subroutine, it can (and does) push the return address onto the stack before it finishes reading the address it's going to jump to."

I hope you appreciate my sincere feedbacks for your invaluable tool, it helped A LOT in the building, understanding and continued usage of Ben's 6502 computer - and also be merciful to me for my less than perfect English and misuses / wrong usage of words.
Andrea

**Comment by Nectivio** [comment] 2022-02-20 22:47
Issue resolved in v1.3.1

**Closed as completed by Nectivio** 2022-02-20 22:47 UTC

**Comment by Nectivio** [comment] 2022-02-20 23:05
I have corrected my monitor ISR.

The sequence from above should now look like this:

    * 800f r 20 b0 
      01ff r 41
      01ff W 80
      01fe W 11
      8011 r 82        JSR $82b0

Showing the correct sequence of reads and writes, and also not showing the decoded instruction until the 5 clock cycles after we read the 0x20 byte since it's not until then that the full operand has been read.
